### ISSUE TITLE
'SuppressException' crash on service config

### ISSUE THREAD

**Issue by elling** [Microsoft/MIMConfigDocumenter#8]
From the error log: 

MIMConfigDocumenterLog Warning: 30000 : MIMConfigDocumenter (1.17.0606.0): 06/08/2017 09:36:33.6754:  Connector SubType: 'PowerShell'. ECMA2 Connector of subtype 'PowerShell' is currently not supported. The connector 'Powershell - Office 365' with be treated as a generic ECMA2 connector.
MIMConfigDocumenterLog Error: 40000 : MIMConfigDocumenter (1.17.0606.0): 06/08/2017 09:37:02.8896: Exception in 'MIMServicePolicyDocumenter : GetReport'. Details: System.Xml.XmlException: 'SuppressException' is an unexpected token. Expecting white space. Line 3, position 114.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(Int32 pos)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.FillWorkflowsSummaryDiffgramDataSet()
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.ProcessWorkflowsSummary()
   at MIMConfigDocumenter.MIMServicePolicyDocumenter.GetReport().

Happens with the portal config.  Sync engine config alone works fine. We've tried the scripts for several customers, same result. All use Soren Granfeldt's Powershell Management Agent. Not sure if that is related tho.

**Comment by NileshGhodekar** [comment]
This is crashing at documenting a workflow activity. Is it possible to share the complete config export? Is yes, email me directly at nileshg at microsoft.com

**Comment by NileshGhodekar** [comment]
In the XOML for workflow "_NO:NC:NOTE : Notify when employee about to expire", SuppressException property is joined to the Bcc property which is resulting in the invalid xoml and correct error message about missing "Expecting white space". Obviously the xoml for this activity is hand-edited.  I'd be surprised if this workflow runs when triggered since the xoml is invalid. I'll close this issue now, but I'll a check for robustness to prevent the complete crash.
